global:
  scrape_interval: 30s
  scrape_timeout: 15s

scrape_configs:
  - job_name: victoriametrics
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: alloy
    static_configs:
      - targets: ['alloy:12345']

  - job_name: pve
    metrics_path: /pve
    scrape_timeout: 25s
    params:
      module: [default]
      cluster: ['1']
      node: ['0']
    static_configs:
      - targets:
          - 192.168.99.2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221

  - job_name: pve-node
    static_configs:
      - targets: ['192.168.99.2:9100']
        labels:
          host: pve

  - job_name: pfsense
    static_configs:
      - targets: ['192.168.99.1:9100']
        labels:
          host: pfsense